version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: "1000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT

  nginx:
    image: nginx
    volumes:
      - ./docker/jsbot.conf.template:/etc/nginx/templates/jsbot.conf.template
    ports:
      - "80:80"
    environment:
      - DOMAIN=$DOMAIN
      - NGINX_PORT=$PORT
    depends_on:
      - app
